import org.apache.spark.{SparkConf, SparkContext}

/**
 * Often each task will generate one file, because we don't know whether
 * the generated file will be small or big, it's better to aggregate them
 * in the end when we do know the sizes.
 *
 * This file will read any text files directory (generated by spark) and merge them as one file
 */
object ReadIntoOneFile {
  def main(args: Array[String]): Unit = {
    val conf = new SparkConf().setAppName("ReadIntoOneFile")
    val sc = new SparkContext(conf)
    val input = args(0) // /user/naward01/domain_count_123456789
    val output = input + "_2" // /user/naward01/domain_count_123456789_2
    sc.textFile(input).coalesce(1).saveAsTextFile(output)
  }
}
